### PR TITLE
Translation in Chinese

### PR DESCRIPTION
**Pull request by hanxi**
there are translate some in chinese. but I see more of words are not in `message.json` like `New` `Open` `Recent` and so on in navabar. and the button like `Choose  your galleries`.

### CODE REVIEW

**Comment by hanxi** [comment]
sorry, only last three commit is useful . I don't know how to delete before commit .

**Comment by hanxi** [comment]
I update it.

**Comment by ArmandGrillet** [comment]
Send me a message when the translation will be finished and I will merge it.

**Comment by hanxi** [comment]
I translate complete it. but the `help input` have some bugs. in  <https://github.com/ArmandGrillet/Mado/blob/master/src/js/Editor/HelpManager.js#L90> limit 3 characters ( I searched it and test, in javascripts, string.length() is not get bytes of string ), a chinese word limit 2 bytes to express. So I think there need to modify.

**Comment by ArmandGrillet** [comment]
We should keep the help part in English, problems with localization of `.length()`in JavaScript seem very hard to solve.

**Comment by hanxi** [comment]
I think let `this.help.val().length>0` do search. solved like this:

delete L90-L101 and L140.

Because such as `Bold` translate to chinese is `粗体`,  the `.length()` is 2. So do search only need `this.help.val().length>0`, when input `粗` then show the result.

**Comment by ArmandGrillet** [comment]
I just found the function `chrome.i18n.getUILanguage()` so I can easily change the value where we display the help depending on the language. Is it OK to display the help when the `this.help.val().length > 1` in Chinese?

**Comment by hanxi** [comment]
yes, I delete L90-L101 and L140. it's works when I input one words can show the result.

**Comment by ArmandGrillet** [comment]
Commit done with a localized help, normally you just need two characters to display the help in Chinese now.

**Comment by hanxi** [comment]
`getUILanguage` in chinese return `zh-CN`. I commit it.

**Comment by ArmandGrillet** [comment]
Thanks, now I think the JS is ready for the localization. Tell me when `zh_CN/messages.json`is completely translated and I will merge your pull request.

**Comment by hanxi** [comment]
Now, I complete all to chinese in `zh_CN/message.json`.

**Comment by hanxi** [comment]
But I saw `setting`,`Q&A`,`Shortcuts`,`About Mado` has no localization in `_locales/`

**Comment by ArmandGrillet** [comment]
I will add the JS code to localize the Settings and Shortcuts page and remove the Q&A page today. The About page won't be translated.






On Thu, Jan 29, 2015 at 5:06 PM -0800, "涵曦" <notifications@github.com> wrote:












But I saw setting,Q&A,Shortcuts,About Mado has no localization in _locales/

**Comment by hanxi** [comment]
:ok_hand:

**Comment by ArmandGrillet** [comment]
Done. `About` is also localized (only the MIT license is still in English). Tell me if there's a problem but normally everything should be OK for the localization!

**Comment by hanxi** [comment]
It's completely translate to chinese. you can merge it now.

**Comment by ArmandGrillet** [comment]
Thank you! I will add a localization in French and publish the new version on the Chrome Web Store in the coming days.

**Pull request merged**
